### ISSUE TITLE
Validate Images

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-jl-notebooks#2]
Are the issues with images resolved now? They look good on my end.

**Comment by jlperla** [comment]
Looks good.  The header, though looks broken?  I thought that was supposed to be fixed? 

![image](https://user-images.githubusercontent.com/13106721/53900768-1ea0c900-3ff2-11e9-85ba-f69e8e0cb42f.png)

I will let you submit a new issue for that if you think there is a regression, or if this simply hasn't been integrated into the latest code.

**Comment by arnavs** [comment]
Great. And no regression, “in practice” we push the notebooks here after we trim the headers out. I just wanted to refresh this repo and confirm the issue.

**Comment by jlperla** [comment]
Perfect.  I think they are now fine as-is until we do the full push of the new (restructured) notebooks.
